[package]
name = "rargs"
version = "0.3.0"
authors = ["Jinzhou Zhang <lotabout@gmail.com>"]
description = "xargs + awk with pattern matching support."
documentation = "https://github.com/lotabout/rargs"
homepage = "https://github.com/lotabout/rargs"
repository = "https://github.com/lotabout/rargs"
readme  = "README.md"
keywords = ["xargs", "awk", "regex", "cli"]
license = "MIT"
edition = "2018"

[dependencies]
regex = "1.10.2"
structopt = "0.3.26"
lazy_static = "1.4.0"
num_cpus = "1.16.0"
threadpool = "1.8.1"

[dev-dependencies]
assert_cli = "0.6.3"
